name: PR Review Summarizer

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
  pull_request_review:
    types: [submitted, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install @octokit/rest node-fetch

      - name: Run review summarizer
        run: node .github/scripts/collect-reviews.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Upload Markdown Summary
        uses: actions/upload-artifact@v4
        with:
          name: review-summary
          path: review_summary_*.md
